name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - run: npm ci

      - run: npm test

  Percy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "src/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  Percy_Storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - run: npm ci

      - run: npm run snapshot
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
