name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm ci

      - run: npm test

  Percy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npx percy snapshot src/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
