name: CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    Percy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: percy/snapshot-action@v0.1.1
              with:
                  build-directory: "src/"
              env:
                  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
